command: [
  "flask",
  "--app", 
  "app_react:flask_app",
  "run",
  "--host=0.0.0.0"
]

env:
  - name: 'DATABRICKS_HTTP_PATH'
    value: '<SQL WAREHOUSE PATH>'
  - name: 'DATABRICKS_SERVER_HOSTNAME'
    value: '<DATABRICKS SERVER HOSTNAME>'

